services:
  master:
    image: redis:latest
    container_name: redis-master
    networks:
      - redis-net

  slave:
    image: redis:latest
    command: redis-server --slaveof redis-master 6379
    depends_on:
    - master
    networks:
      - redis-net

  sentinel:
    build:
      context: ./sentinel
      dockerfile: Dockerfile
    environment:
    - SENTINEL_DOWN_AFTER=5000
    - SENTINEL_FAILOVER=5000
    depends_on:
    - master
    - slave
    networks:
      - redis-net

networks:
  redis-net:
    driver: bridge
